title: BriqueParBrique
description: L'essentiel du développement, une étape à la fois.
url: https://briqueparbrique.github.io

goatcounter:
  code: briqueparbrique

exclude:
  - README.md
  - DEVELOPER.md
  - CONTRIBUTING.md
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - justfile
  - LICENSE
